server:
  port: 8090
  servlet:
    context-path: /auth
    session:
      cookie:
        path: /auth

auth-service:
  oauth:
    clientId: TaskManager-1, Account-1
    clientSecret: fDw7Mpkk5czHNuSRtmhGmAGL42CaxQB9, fDw7Mpkk5czHNuSRtmhGmAGL42Ca21321
    redirectUris: http://localhost:9000/taskmanager/login/oauth2/code/taskmanagerclient, http://localhost:9090/accounting/login/oauth2/code/accountingclient

spring:
  profiles:
    active: local
  kafka:
    properties:
      schema.registry.url: http://localhost:8081
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer

  datasource:
    driver-class-name: org.postgresql.Driver
    username: root
    password: iamgroot
    url: jdbc:postgresql://localhost:5687/auth-db
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
    open-in-view: false
    properties:
      hibernate:
        generate_statistics: false
        order_updates: true
        order_inserts: true
    show-sql: false
  servlet:
    multipart:
      max-file-size: 15MB
      max-request-size: 15MB
logging:
  level:
    org.springframework: debug
    com.auth.service: warn
    com.zaxxer.hikari: warn
    org.hibernate: warn
    org.apache: warn

