version: '3.1'

services:

  accounting-db:
    image: postgres:11.3-alpine
    restart: always
    ports:
      - 5677:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: iamgroot
      POSTGRES_DB: accounting-db
    container_name: accounting-db
